import type { TemplateDefinitionInput } from "../types";

/** T2 — Mascot story: introduction → escalating eras → transformation → finale. */
export const mascotStory: TemplateDefinitionInput = {
  id: "mascot-story",
  family: "mascot-story",
  name: "Mascot Story",
  description: "Your mascot travels through escalating eras to a transformation and a finale. The character is drawn from a persistent reference (your cutout, or a code-drawn vector mascot) so it stays the same in every scene.",
  version: 1,
  tags: { purpose: ["brand", "story", "kids", "social"], generatedMedia: "optional" },
  defaultAspect: "16:9",
  supportedAspects: ["16:9", "9:16", "1:1"],
  duration: { minSec: 20, maxSec: 60, defaultSec: 35 },
  inputs: [
    { id: "characterName", label: "Character name", kind: "text", required: true, maxLength: 40 },
    { id: "characterImage", label: "Character cutout (optional, transparent PNG)", kind: "image", help: "Leave empty to use a code-drawn vector mascot in your colours." },
    { id: "species", label: "Vector mascot shape", kind: "select", options: ["blob", "cat", "bear", "bird", "robot"], default: "blob" },
    { id: "color", label: "Character colour (#rrggbb)", kind: "text", maxLength: 7, default: "" },
    { id: "theme", label: "Story theme", kind: "text", required: true, maxLength: 80 },
    { id: "eras", label: "Eras / steps (2–4)", kind: "list", required: true, maxItems: 4, help: "Each becomes an escalating scene." },
    { id: "transformation", label: "Transformation moment", kind: "text", required: true, maxLength: 80 },
    { id: "finale", label: "Finale line / CTA", kind: "text", maxLength: 60 },
    { id: "logo", label: "Logo", kind: "image" },
    { id: "music", label: "Music (optional)", kind: "audio" },
  ],
  character: { nameInput: "characterName", imageInput: "characterImage", speciesInput: "species", colorInput: "color" },
  scenes: [
    {
      slot: "intro",
      purpose: "Introduction",
      durationSec: 5,
      layout: "character-stage",
      background: { type: "gradient", from: "brand.background", to: "brand.primary", angle: 160 },
      motion: 0.5,
      layers: [
        { kind: "shape", slot: "decor", shape: "blob", color: "brand.accent", animation: "fade", loop: "drift", box: { x: 0.25, y: 0.05, w: 0.5, h: 0.9 } },
        { kind: "character", slot: "media", pose: "wave", animation: "pop" },
        { kind: "text", slot: "headline", role: "headline", text: "Meet {{characterName}}", animation: "rise" },
        { kind: "text", slot: "label", role: "label", text: "{{theme}}", animation: "fade", delaySec: 0.6 },
      ],
    },
    {
      slot: "era",
      purpose: "Era {{index}}: {{item}}",
      durationSec: 6,
      layout: "character-stage",
      repeatFor: "eras",
      transition: { type: "slide", durationFrames: 10 },
      background: { type: "gradient", from: "brand.secondary", to: "brand.background", angle: 180 },
      motion: 0.6,
      layers: [
        { kind: "shape", slot: "prop", shape: "circle", color: "brand.accent", animation: "pop", loop: "pulse" },
        { kind: "shape", slot: "prop2", shape: "rect", color: "brand.secondary", animation: "pop", loop: "drift", delaySec: 0.2 },
        { kind: "character", slot: "media", pose: "walk", animation: "slide" },
        { kind: "text", slot: "headline", role: "headline", text: "{{item}}", animation: "rise", delaySec: 0.2 },
        { kind: "text", slot: "label", role: "label", text: "{{index}} / {{count}}", animation: "fade" },
      ],
    },
    {
      slot: "transformation",
      purpose: "Transformation",
      durationSec: 6,
      layout: "character-stage",
      transition: { type: "zoom", durationFrames: 12 },
      background: { type: "gradient", from: "brand.accent", to: "brand.primary", angle: 200 },
      motion: 1,
      layers: [
        { kind: "shape", slot: "decor", shape: "ring", color: "brand.accent", animation: "pop", loop: "spin", box: { x: 0.2, y: -0.2, w: 0.6, h: 1.4 } },
        { kind: "character", slot: "media", pose: "celebrate", accessory: "cape", scale: 1.1, animation: "pop" },
        { kind: "text", slot: "headline", role: "headline", text: "{{transformation}}", animation: "pop", delaySec: 0.4 },
      ],
    },
    {
      slot: "finale",
      purpose: "Finale",
      durationSec: 5,
      layout: "end-card",
      transition: { type: "fade", durationFrames: 12 },
      background: { type: "gradient", from: "brand.primary", to: "brand.background", angle: 160 },
      motion: 0.6,
      layers: [
        { kind: "image", slot: "media", asset: "{{logo}}", optional: true, fit: "contain", animation: "pop" },
        { kind: "text", slot: "headline", role: "headline", text: "{{characterName}}", animation: "rise" },
        { kind: "text", slot: "cta", role: "cta", text: "{{finale}}", optional: true, animation: "pop", delaySec: 0.4 },
      ],
    },
  ],
  audio: { musicInput: "music", musicGainDb: -8, duckDb: -12, narration: "optional", captions: false, musicLocked: false },
  providers: { required: [], optional: ["image-generation", "tts"] },
  profile: { name: "Story", pacing: "balanced", motionIntensity: 0.65, transition: "slide" },
  checklist: ["Same character reference in every scene", "Eras escalate toward the transformation", "Backgrounds editable without replacing the character"],
};
