import type { TemplateDefinitionInput } from "../types";

/** T1 — Motion graphics reel. Code-only type and shape animation; generated footage not needed. */
export const motionReel: TemplateDefinitionInput = {
  id: "motion-reel",
  family: "motion-reel",
  name: "Motion Graphics Reel",
  description: "Hook → kinetic typography → graphic progression → focal reveal → end card. Five distinct visual beats built from real type and shape animation, with your logo and music.",
  version: 4,
  tags: { purpose: ["brand", "social", "announcement"], generatedMedia: "none" },
  defaultAspect: "16:9",
  supportedAspects: ["16:9", "9:16", "1:1"],
  duration: { minSec: 10, maxSec: 45, defaultSec: 20 },
  inputs: [
    { id: "headline", label: "Headline / message", kind: "text", required: true, maxLength: 90 },
    { id: "brandName", label: "Brand name", kind: "text", required: true, maxLength: 40 },
    { id: "hook", label: "Opening hook (a few words)", kind: "text", required: true, maxLength: 40 },
    { id: "points", label: "Three short points", kind: "list", maxItems: 3, help: "Shown as a kinetic sequence. Keep each under five words." },
    { id: "focal", label: "Focal statement", kind: "text", maxLength: 60, help: "The one line you want remembered." },
    { id: "heroImage", label: "Focal image (optional)", kind: "image" },
    { id: "logo", label: "Logo", kind: "image" },
    { id: "cta", label: "End-card line", kind: "text", maxLength: 40 },
    { id: "music", label: "Music track", kind: "audio" },
    { id: "durationSec", label: "Duration (seconds)", kind: "number", default: 20 },
  ],
  scenes: [
    {
      slot: "hook",
      purpose: "Immediate hook",
      durationSec: 3,
      layout: "kinetic",
      background: { type: "color", color: "brand.background" },
      motion: 0.9,
      layers: [
        // A liquid shape melting from form to form behind the hook (Skia shader); calm: a pulsing circle.
        { kind: "graphics", slot: "decor", backend: "skia", component: "liquid-morph", componentVersion: 1, minMotion: 0.5, params: { sequence: "circle,squircle,star,blob", holdSec: 0.5, morphSec: 0.6, colors: "brand.primary", fill: 0.7, wobble: 1, gloss: 0.9, glow: true }, box: { x: 0.3, y: 0.1, w: 0.4, h: 0.8 } },
        { kind: "shape", slot: "decor", shape: "circle", color: "brand.primary", animation: "pop", loop: "pulse", maxMotion: 0.49, box: { x: 0.35, y: 0.2, w: 0.3, h: 0.6 } },
        { kind: "text", slot: "headline", role: "headline", text: "{{hook}}", scale: 1.35, animation: "pop", uppercase: true },
      ],
    },
    {
      slot: "kinetic",
      purpose: "Kinetic typography",
      durationSec: 5,
      layout: "kinetic",
      // The hook flies past the camera onto the kinetic type (motion grammar: foreground fly-through).
      transition: { type: "flythrough", durationFrames: 14 },
      background: { type: "gradient", from: "brand.primary", to: "brand.secondary", angle: 120 },
      motion: 0.95,
      layers: [
        { kind: "graphics", slot: "decor", backend: "skia", component: "aurora", componentVersion: 1, minMotion: 0.5, params: { colors: "brand.primary,brand.primary,brand.background", base: "brand.background", speed: 1, scale: 1.6, intensity: 0.5 }, box: { x: 0, y: 0, w: 1, h: 1 } },
        { kind: "text", slot: "kicker", role: "kicker", text: "{{brandName}}", animation: "fade" },
        { kind: "text", slot: "headline", role: "headline", text: "{{headline}}", animation: "type", stagger: true, scale: 1.15 },
      ],
    },
    {
      slot: "progression",
      purpose: "Graphic progression",
      durationSec: 5,
      layout: "benefit-list",
      transition: { type: "liquid", durationFrames: 16 },
      calmTransition: { type: "wipe", durationFrames: 10 },
      background: { type: "color", color: "brand.background" },
      motion: 0.85,
      layers: [
        { kind: "shape", slot: "media", shape: "bars", color: "brand.accent", animation: "rise" },
        { kind: "text", slot: "headline", role: "kicker", text: "{{brandName}}", scale: 1.4, animation: "fade" },
        { kind: "text", slot: "item1", role: "subhead", text: "{{points[0]}}", optional: true, animation: "slide", delaySec: 0.3 },
        { kind: "text", slot: "item2", role: "subhead", text: "{{points[1]}}", optional: true, animation: "slide", delaySec: 1.2 },
        { kind: "text", slot: "item3", role: "subhead", text: "{{points[2]}}", optional: true, animation: "slide", delaySec: 2.1 },
      ],
    },
    {
      slot: "reveal",
      purpose: "Focal reveal",
      durationSec: 4,
      layout: "fullbleed-media",
      when: "heroImage",
      transition: { type: "lens", durationFrames: 18 },
      calmTransition: { type: "zoom", durationFrames: 12 },
      background: { type: "color", color: "brand.surface" },
      motion: 0.7,
      layers: [
        { kind: "image", slot: "media", asset: "{{heroImage}}", fit: "cover", animation: "fade", kenBurns: true },
        { kind: "text", slot: "headline", role: "label", text: "{{brandName}}", optional: true, backing: "translucent", animation: "rise", delaySec: 0.5 },
      ],
    },
    {
      slot: "statement",
      purpose: "Focal statement",
      durationSec: 3,
      layout: "stat-focus",
      when: "focal",
      transition: { type: "grain", durationFrames: 14 },
      calmTransition: { type: "fade", durationFrames: 10 },
      background: { type: "gradient", from: "brand.secondary", to: "brand.background", angle: 200 },
      motion: 0.7,
      layers: [
        { kind: "shape", slot: "decor", shape: "ring", color: "brand.accent", animation: "pop", loop: "spin", box: { x: 0.15, y: -0.25, w: 0.7, h: 1.5 } },
        { kind: "text", slot: "headline", role: "headline", text: "{{focal}}", scale: 1.1, backing: "translucent", animation: "pop" },
      ],
    },
    {
      slot: "endcard",
      purpose: "End card",
      durationSec: 3,
      layout: "end-card",
      transition: { type: "morph", durationFrames: 20 },
      calmTransition: { type: "zoom", durationFrames: 10 },
      background: { type: "gradient", from: "brand.primary", to: "brand.background", angle: 160 },
      motion: 0.6,
      layers: [
        { kind: "graphics", slot: "decor", backend: "skia", component: "mesh-gradient", componentVersion: 1, minMotion: 0.5, seed: 2, params: { colors: "brand.primary,brand.background,brand.background,brand.primary", speed: 0.25, softness: 1.8, warp: 0.45 }, box: { x: 0, y: 0, w: 1, h: 1 } },
        { kind: "image", slot: "media", asset: "{{logo}}", optional: true, fit: "contain", animation: "pop" },
        { kind: "text", slot: "headline", role: "headline", text: "{{brandName}}", animation: "rise", delaySec: 0.2 },
        { kind: "text", slot: "cta", role: "cta", text: "{{cta}}", optional: true, animation: "pop", delaySec: 0.5 },
      ],
    },
  ],
  profile: { pacing: "fast", transition: "slide", motionIntensity: 0.8 },
  audio: { musicInput: "music", musicGainDb: -4, duckDb: -10, narration: "none", captions: false, musicLocked: false },
  providers: { required: [], optional: ["planner", "graphics-skia"] },
  plannerGuidance: "Five beats: hook (≤3 words), kinetic headline, three-point graphic progression, focal reveal, end card. Words are the visuals: short, punchy, no invented claims.",
  checklist: ["Five visually distinct beats", "No unintended blank frames", "Brand name and logo substituted", "Readable copy at every aspect"],
};

/** P2 — Brand/Channel Showreel: a preset of the motion reel family (section 21). */
export const brandShowreel: TemplateDefinitionInput = {
  id: "brand-showreel",
  family: "motion-reel",
  preset: "P2",
  name: "Brand / Channel Showreel",
  description: "One colour motif carried from an opening circle through a thumbnail wall and a hero milestone to your logo. Uses only supplied facts; generated assets off by default.",
  version: 4,
  tags: { purpose: ["brand", "channel", "showreel"], generatedMedia: "none" },
  defaultAspect: "16:9",
  supportedAspects: ["16:9", "9:16", "1:1"],
  duration: { minSec: 10, maxSec: 45, defaultSec: 15 },
  inputs: [
    { id: "channelName", label: "Channel or brand name", kind: "text", required: true, maxLength: 40 },
    { id: "promise", label: "Promise line", kind: "text", required: true, maxLength: 70 },
    { id: "thumbnails", label: "Thumbnails / work samples", kind: "images", maxItems: 6, required: true },
    { id: "hero", label: "Hero milestone image", kind: "image", required: true },
    { id: "milestone", label: "Milestone (only a supplied fact)", kind: "facts", maxItems: 1 },
    { id: "logo", label: "Logo", kind: "image" },
    { id: "cta", label: "End line / CTA", kind: "text", maxLength: 40 },
    { id: "music", label: "Music track", kind: "audio" },
    { id: "durationSec", label: "Duration (seconds)", kind: "number", default: 15 },
  ],
  scenes: [
    {
      slot: "motif",
      purpose: "Motif / hook",
      durationSec: 2,
      layout: "title-center",
      background: { type: "color", color: "brand.background" },
      motion: 0.9,
      layers: [
        { kind: "graphics", slot: "decor", backend: "redraw", component: "ribbon", componentVersion: 1, params: { path: "circle", width: 40, drawSec: 1.6, glow: 20 } },
        { kind: "text", slot: "headline", role: "headline", text: "{{channelName}}", animation: "fade", delaySec: 0.6 },
      ],
    },
    {
      slot: "wall",
      purpose: "Thumbnail wall",
      durationSec: 4,
      layout: "media-grid",
      transition: { type: "zoom", durationFrames: 9 },
      background: { type: "color", color: "brand.background" },
      motion: 0.8,
      layers: [
        { kind: "image", slot: "media", asset: "{{thumbnails[0]}}", optional: true, fit: "cover", frame: "rounded", animation: "pop", delaySec: 0 },
        { kind: "image", slot: "media2", asset: "{{thumbnails[1]}}", optional: true, fit: "cover", frame: "rounded", animation: "pop", delaySec: 0.15 },
        { kind: "image", slot: "media3", asset: "{{thumbnails[2]}}", optional: true, fit: "cover", frame: "rounded", animation: "pop", delaySec: 0.3 },
        { kind: "image", slot: "media4", asset: "{{thumbnails[3]}}", optional: true, fit: "cover", frame: "rounded", animation: "pop", delaySec: 0.45 },
        { kind: "image", slot: "media5", asset: "{{thumbnails[4]}}", optional: true, fit: "cover", frame: "rounded", animation: "pop", delaySec: 0.6 },
        { kind: "image", slot: "media6", asset: "{{thumbnails[5]}}", optional: true, fit: "cover", frame: "rounded", animation: "pop", delaySec: 0.75 },
      ],
    },
    {
      slot: "hero",
      purpose: "Hero milestone",
      durationSec: 3,
      layout: "fullbleed-media",
      transition: { type: "portal", durationFrames: 14 },
      background: { type: "color", color: "brand.surface" },
      motion: 0.6,
      layers: [
        { kind: "image", slot: "media", asset: "{{hero}}", fit: "cover", animation: "fade", kenBurns: true },
        { kind: "text", slot: "headline", role: "headline", text: "{{milestone[0]}}", factFrom: "milestone[0]", optional: true, backing: "translucent", animation: "rise", delaySec: 0.4 },
      ],
    },
    {
      slot: "promise",
      purpose: "Promise",
      durationSec: 3,
      layout: "kinetic",
      transition: { type: "wipe", durationFrames: 9 },
      background: { type: "gradient", from: "brand.primary", to: "brand.secondary", angle: 135 },
      motion: 0.9,
      layers: [{ kind: "text", slot: "headline", role: "headline", text: "{{promise}}", animation: "type", stagger: true }],
    },
    {
      slot: "logo",
      purpose: "Logo / CTA",
      durationSec: 3,
      layout: "end-card",
      transition: { type: "colorfield", durationFrames: 18 },
      background: { type: "color", color: "brand.background" },
      motion: 0.6,
      layers: [
        { kind: "graphics", slot: "decor", backend: "redraw", component: "ribbon", componentVersion: 1, params: { path: "swoosh", width: 30, drawSec: 1.2, glow: 16 }, box: { x: 0.08, y: 0.74, w: 0.84, h: 0.22 } },
        { kind: "image", slot: "media", asset: "{{logo}}", optional: true, fit: "contain", animation: "pop", delaySec: 0.3 },
        { kind: "text", slot: "headline", role: "headline", text: "{{channelName}}", animation: "rise", delaySec: 0.4 },
        { kind: "text", slot: "cta", role: "cta", text: "{{cta}}", optional: true, animation: "pop", delaySec: 0.7 },
      ],
    },
  ],
  profile: { pacing: "fast", transition: "zoom", motionIntensity: 0.85 },
  audio: { musicInput: "music", musicGainDb: -4, duckDb: -10, narration: "none", captions: false, musicLocked: false },
  providers: { required: [], optional: ["planner", "graphics-redraw"] },
  plannerGuidance:
    "Example beat plan: 0–2 s motif/hook; 2–6 s thumbnail wall; 6–9 s hero milestone; 9–12 s promise; 12–15 s logo/CTA. Suggest the strongest hero image and explain why in warnings. Use only supplied facts; never invent subscriber counts or achievements.",
  checklist: ["Motif carried from opening to logo", "Milestone text is a supplied fact", "Logo is the approved asset, undistorted"],
};
