import type { TemplateDefinitionInput } from "../types";

/** T3 — Product launch. Code-only: uploaded screenshots, logo and music; no generation provider needed. */
export const productLaunch: TemplateDefinitionInput = {
  id: "product-launch",
  family: "product-launch",
  name: "Product Launch",
  description:
    "Problem → product reveal → approved benefits → a screen demo of your product → proof (only if you supply it) → call to action. Uses your screenshots, logo, brand kit and music.",
  version: 4,
  tags: { purpose: ["launch", "marketing"], generatedMedia: "none" },
  defaultAspect: "16:9",
  supportedAspects: ["16:9", "9:16", "1:1"],
  duration: { minSec: 15, maxSec: 60, defaultSec: 30 },
  inputs: [
    { id: "productName", label: "Product name", kind: "text", required: true, maxLength: 60 },
    { id: "promise", label: "One-line promise", kind: "text", required: true, maxLength: 140, help: "What the product does for the viewer, in one line." },
    { id: "problem", label: "Problem / hook", kind: "text", required: true, maxLength: 120, help: "The pain point that opens the video." },
    { id: "benefits", label: "Approved benefits (up to 3)", kind: "facts", required: true, maxItems: 3, help: "Shown verbatim. Only claims you approve." },
    { id: "proof", label: "Proof (optional)", kind: "facts", maxItems: 1, help: "A real quote or metric you can source. Omitted when empty — never invented." },
    { id: "proofSource", label: "Proof source", kind: "text", maxLength: 80 },
    { id: "screenshots", label: "Screenshots / product media", kind: "images", maxItems: 4 },
    { id: "logo", label: "Logo", kind: "image" },
    { id: "cta", label: "Call to action", kind: "text", required: true, maxLength: 40 },
    { id: "destinationUrl", label: "Destination URL", kind: "url", maxLength: 120 },
    { id: "music", label: "Music track", kind: "audio" },
    { id: "audience", label: "Audience", kind: "text", maxLength: 120 },
    { id: "durationSec", label: "Duration (seconds)", kind: "number", default: 30 },
  ],
  scenes: [
    {
      slot: "hook",
      purpose: "Problem / hook",
      durationSec: 5,
      layout: "kinetic",
      background: { type: "gradient", from: "brand.background", to: "brand.secondary", angle: 140 },
      motion: 0.7,
      narration: "{{problem}}",
      layers: [
        // Lively projects open on a living brand-colour gradient (Skia shader); calm ones on the drifting blob.
        { kind: "graphics", slot: "decor", backend: "skia", component: "mesh-gradient", componentVersion: 1, minMotion: 0.5, params: { colors: "brand.background,brand.primary,brand.background,brand.background", speed: 0.22, softness: 1.8, warp: 0.5 }, box: { x: 0, y: 0, w: 1, h: 1 } },
        { kind: "shape", slot: "decor", shape: "blob", color: "brand.primary", animation: "fade", loop: "drift", maxMotion: 0.49, box: { x: 0.55, y: -0.1, w: 0.6, h: 0.9 } },
        { kind: "text", slot: "kicker", role: "kicker", text: "{{audience}}", optional: true, animation: "fade" },
        { kind: "text", slot: "headline", role: "headline", text: "{{problem}}", animation: "type", stagger: true, scale: 1.1 },
      ],
    },
    {
      slot: "reveal",
      purpose: "Product reveal",
      durationSec: 6,
      layout: "hero-split",
      // The product floods in behind a liquid front (shader transition).
      transition: { type: "liquid", durationFrames: 18 },
      calmTransition: { type: "wipe", durationFrames: 12 },
      background: { type: "color", color: "brand.background" },
      motion: 0.6,
      narration: "Meet {{productName}}. {{promise}}",
      layers: [
        { kind: "shape", slot: "decor", shape: "grid", color: "brand.muted", animation: "fade" },
        { kind: "text", slot: "kicker", role: "kicker", text: "Introducing", animation: "fade" },
        { kind: "text", slot: "headline", role: "headline", text: "{{productName}}", animation: "rise", delaySec: 0.2 },
        { kind: "text", slot: "subhead", role: "subhead", text: "{{promise}}", animation: "rise", delaySec: 0.5 },
        { kind: "image", slot: "media", asset: "{{screenshots[0]}}", frame: "laptop", fit: "cover", animation: "slide", delaySec: 0.3, alt: "Product screenshot" },
      ],
    },
    {
      slot: "benefits",
      purpose: "Benefits",
      durationSec: 9,
      layout: "benefit-list",
      transition: { type: "fade", durationFrames: 12 },
      background: { type: "gradient", from: "brand.background", to: "brand.surface", angle: 180 },
      motion: 0.55,
      narration: "{{benefits}}",
      layers: [
        { kind: "text", slot: "headline", role: "headline", text: "Why {{productName}}", scale: 0.7, animation: "rise" },
        { kind: "text", slot: "item1", role: "body", text: "{{benefits[0]}}", factFrom: "benefits[0]", optional: true, backing: "solid", animation: "slide", delaySec: 0.4 },
        { kind: "text", slot: "item2", role: "body", text: "{{benefits[1]}}", factFrom: "benefits[1]", optional: true, backing: "solid", animation: "slide", delaySec: 1.6 },
        { kind: "text", slot: "item3", role: "body", text: "{{benefits[2]}}", factFrom: "benefits[2]", optional: true, backing: "solid", animation: "slide", delaySec: 2.8 },
        // A glass lens drifts over the product detail (Skia shader); calm projects show the still card.
        { kind: "graphics", slot: "media", backend: "skia", component: "glass-lens", componentVersion: 1, minMotion: 0.5, params: { image: "{{screenshots[1]}}", path: "drift", lensSize: 0.3, magnify: 1.5, chroma: 0.35 } },
        { kind: "image", slot: "media", asset: "{{screenshots[1]}}", optional: true, maxMotion: 0.49, frame: "card", fit: "contain", animation: "pop", delaySec: 0.2, kenBurns: true, alt: "Product detail" },
      ],
    },
    {
      // Screen demo: a cursor works the real screenshot while the camera follows it. Its steps
      // are planned in the Scene tab (click points, or Claude picks them); until then it holds.
      slot: "demo",
      purpose: "Product demo",
      durationSec: 7,
      layout: "screen-demo",
      when: "screenshots",
      // A glass lens drifts in and opens onto the demo (shader transition).
      transition: { type: "lens", durationFrames: 20 },
      calmTransition: { type: "zoom", durationFrames: 14 },
      background: { type: "color", color: "brand.background" },
      motion: 0.5,
      narration: "",
      demo: { layer: "media" },
      layers: [
        { kind: "text", slot: "headline", role: "headline", text: "{{productName}} in action", scale: 0.55, animation: "rise" },
        { kind: "image", slot: "media", asset: "{{screenshots[0]}}", fit: "contain", animation: "fade", alt: "Product screen" },
      ],
    },
    {
      slot: "proof",
      purpose: "Proof",
      durationSec: 5,
      layout: "quote",
      when: "proof",
      transition: { type: "grain", durationFrames: 16 },
      calmTransition: { type: "fade", durationFrames: 12 },
      background: { type: "color", color: "brand.surface" },
      motion: 0.4,
      narration: "",
      layers: [
        { kind: "text", slot: "quote", role: "quote", text: "“{{proof[0]}}”", factFrom: "proof[0]", animation: "fade" },
        { kind: "text", slot: "label", role: "label", text: "{{proofSource}}", optional: true, animation: "fade", delaySec: 0.6 },
      ],
    },
    {
      slot: "cta",
      purpose: "Call to action",
      durationSec: 5,
      layout: "end-card",
      // The demo shrinks into a shape that opens onto the end card (shader transition).
      transition: { type: "morph", durationFrames: 22 },
      calmTransition: { type: "portal", durationFrames: 14 },
      background: { type: "gradient", from: "brand.primary", to: "brand.background", angle: 160 },
      motion: 0.5,
      narration: "{{cta}}",
      layers: [
        { kind: "graphics", slot: "decor", backend: "skia", component: "mesh-gradient", componentVersion: 1, minMotion: 0.5, seed: 2, params: { colors: "brand.primary,brand.background,brand.background,brand.primary", speed: 0.2, softness: 1.8, warp: 0.45 }, box: { x: 0, y: 0, w: 1, h: 1 } },
        { kind: "image", slot: "media", asset: "{{logo}}", optional: true, fit: "contain", animation: "pop", alt: "Logo" },
        { kind: "text", slot: "headline", role: "headline", text: "{{productName}}", scale: 0.9, animation: "rise", delaySec: 0.2 },
        { kind: "text", slot: "cta", role: "cta", text: "{{cta}}", animation: "pop", delaySec: 0.6 },
        { kind: "text", slot: "label", role: "label", text: "{{destinationUrl}}", optional: true, animation: "fade", delaySec: 0.9 },
      ],
    },
  ],
  profile: { pacing: "balanced", transition: "fade" },
  audio: { musicInput: "music", musicGainDb: -6, duckDb: -12, narration: "optional", captions: false, musicLocked: false },
  providers: { required: [], optional: ["planner", "tts", "graphics-skia"] },
  plannerGuidance:
    "Structure: problem/hook → product reveal → benefits → screen demo (when screenshots are supplied) → proof (only when supplied) → CTA. Use approved benefits verbatim; never invent metrics, testimonials or customer names. Keep headlines under 8 words. Screenshots go in media slots; do not describe features the brief does not state.",
  checklist: [
    "Logo appears on the end card",
    "Every benefit is an approved claim, shown verbatim",
    "Proof scene only exists when proof was supplied",
    "CTA is readable for at least 2 seconds",
    "Music is present and fades at the end",
  ],
};
