import type { TemplateDefinitionInput } from "../types";

/** T4 — Vertical short with voiceover. Narration per scene; captions timed from the actual narration audio. */
export const verticalShort: TemplateDefinitionInput = {
  id: "vertical-short",
  family: "vertical-short",
  name: "Vertical Short with Voiceover",
  description: "Hook → value points → evidence (only if supplied) → CTA, in 9:16 with narration, burned-in captions and platform-safe guides.",
  version: 1,
  tags: { purpose: ["social", "explainer", "marketing"], generatedMedia: "none" },
  defaultAspect: "9:16",
  supportedAspects: ["9:16", "1:1", "16:9"],
  duration: { minSec: 20, maxSec: 60, defaultSec: 35 },
  inputs: [
    { id: "hook", label: "Hook (first line spoken and shown)", kind: "text", required: true, maxLength: 80 },
    { id: "points", label: "Value points (one per scene)", kind: "list", required: true, maxItems: 4, help: "Each becomes a scene with its own narration line." },
    { id: "evidence", label: "Evidence / example (optional, approved)", kind: "facts", maxItems: 1 },
    { id: "cta", label: "Call to action", kind: "text", required: true, maxLength: 60 },
    { id: "brandName", label: "Brand or channel name", kind: "text", maxLength: 40 },
    { id: "visuals", label: "Supporting images (optional)", kind: "images", maxItems: 4 },
    { id: "logo", label: "Logo", kind: "image" },
    { id: "narration", label: "Uploaded narration (optional)", kind: "audio", help: "Leave empty to synthesise narration per scene from the script." },
    { id: "music", label: "Background music", kind: "audio" },
    { id: "durationSec", label: "Target duration (seconds)", kind: "number", default: 35 },
  ],
  scenes: [
    {
      slot: "hook",
      purpose: "Hook",
      durationSec: 5,
      layout: "kinetic",
      background: { type: "gradient", from: "brand.primary", to: "brand.background", angle: 170 },
      motion: 0.85,
      narration: "{{hook}}",
      layers: [
        { kind: "text", slot: "kicker", role: "kicker", text: "{{brandName}}", optional: true, animation: "fade" },
        { kind: "text", slot: "headline", role: "headline", text: "{{hook}}", animation: "type", stagger: true, scale: 1.05 },
      ],
    },
    {
      slot: "point",
      purpose: "Point {{index}}",
      durationSec: 6,
      layout: "hero-split",
      repeatFor: "points",
      transition: { type: "slide", durationFrames: 8 },
      background: { type: "color", color: "brand.background" },
      motion: 0.8,
      narration: "{{item}}",
      layers: [
        { kind: "text", slot: "kicker", role: "kicker", text: "{{index}} / {{count}}", animation: "fade" },
        { kind: "text", slot: "headline", role: "headline", text: "{{item}}", scale: 0.8, animation: "rise" },
        { kind: "image", slot: "media", asset: "{{visuals[i]}}", optional: true, fit: "cover", frame: "rounded", animation: "pop", kenBurns: true },
      ],
    },
    {
      slot: "evidence",
      purpose: "Evidence",
      durationSec: 5,
      layout: "quote",
      when: "evidence",
      transition: { type: "fade", durationFrames: 8 },
      background: { type: "color", color: "brand.surface" },
      motion: 0.5,
      narration: "{{evidence[0]}}",
      layers: [{ kind: "text", slot: "quote", role: "quote", text: "{{evidence[0]}}", factFrom: "evidence[0]", animation: "fade" }],
    },
    {
      slot: "cta",
      purpose: "Call to action",
      durationSec: 5,
      layout: "end-card",
      transition: { type: "zoom", durationFrames: 8 },
      background: { type: "gradient", from: "brand.secondary", to: "brand.primary", angle: 160 },
      motion: 0.6,
      narration: "{{cta}}",
      layers: [
        { kind: "image", slot: "media", asset: "{{logo}}", optional: true, fit: "contain", animation: "pop" },
        { kind: "text", slot: "headline", role: "headline", text: "{{brandName}}", optional: true, animation: "rise" },
        { kind: "text", slot: "cta", role: "cta", text: "{{cta}}", animation: "pop", delaySec: 0.4 },
      ],
    },
  ],
  profile: { pacing: "fast", transition: "slide", motionIntensity: 0.8, framing: "full" },
  audio: { musicInput: "music", narrationInput: "narration", musicGainDb: -10, duckDb: -14, narration: "required", captions: true, musicLocked: false },
  providers: { required: ["tts"], optional: ["planner"] },
  plannerGuidance: "Hook in the first second. One idea per scene, narrated in one or two short sentences (about 2.5 words per second). Evidence only if supplied. The CTA must be spoken and shown.",
  checklist: ["Narration fits each scene", "Captions stay inside the safe area", "CTA visible and not covered by platform UI", "First frame readable"],
};
